### ISSUE TITLE
Generate a congestive heart failure dataset and explore with Jupyter

### ISSUE THREAD

**Issue by rcurrie** [anthem-ai/ucsc-engineering-2020#1]
Let's get started by creating a dataset and exploring via Jupyter:

- [x] Send @rcurrie your github id so he can add you to this repo
- [x] Clone the repo and create a sub-folder using your github id as a name - this is where you'll do individual work.
- [x] Create a script to generate a set of FHIR JSON records modeling a cohort of patients with congestive heart failure using [Synthea](https://synthetichealth.github.io/module-builder/#congestive_heart_failure)
- [x] Create a Jupyter notebook that loads a portion of the cohorts data i.e. metabolic panels or vital signs
- [x] Calculate various summary statistics on the subset of data

**Comment by shayanshaikh** [comment]
add @shayanshaikh

**Comment by strs1byn99** [comment]
add @strs1byn99

**Comment by breillyl** [comment]
Could you also add @breillyl

**Comment by CassidyNorfleet** [comment]
@CassidyNorfleet

**Comment by prasadaman2000** [comment]
Hi! My username is @prasadaman2000

**Comment by harshithaarul** [comment]
Hi Rob! Please add @harshithaarul
